<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsUraPlugin>true</IsUraPlugin>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>2026.3.9</Version>
		<!-- 自动把本插件的 NuGet 运行时依赖闭包拷到输出。 -->
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

		<!-- URA 插件元数据 -->
		<PluginInternalName>EventLoggerPlugin</PluginInternalName>
		<PluginDisplayName>记录事件信息&amp;干劲等</PluginDisplayName>
		<PluginAuthor>xulai1001</PluginAuthor>
		<PluginDescription>记录掉干劲的次数，事件加的属性，走完率等</PluginDescription>
		<PluginRepositoryUrl>https://github.com/URA-Plugins/EventLoggerPlugin</PluginRepositoryUrl>
		<PluginDependencies>LegendScenarioAnalyzer,RamenScenarioAnalyzer</PluginDependencies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MathNet.Numerics" Version="5.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="deps\LegendScenarioAnalyzer\LegendScenarioAnalyzer.csproj">
			<Private>false</Private>
		</ProjectReference>
		<ProjectReference Include="deps\RamenScenarioAnalyzer\RamenScenarioAnalyzer.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="UmamusumeResponseAnalyzer" Version="*" PrivateAssets="all" />
	</ItemGroup>

</Project>
